### ISSUE TITLE
How about using more that two sites?

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/sso#4]
I have 4 sites using the same users table, but I can only sso with two of them. Woudl it bo possible to use more than two sites for the same sso secret key?

**Comment by alanmels** [comment]
@robertgarrigos, We initially built this module with a specific use case in mind, involving just two sites, so the current functionality is limited to that setup. Extending it to cover more sites is definitely possible, but at the moment, our workload is quite high, and we're unable to take on additional development. However, I’d be happy to review and accept a Pull Request if someone else can work on extending the module to support multiple sites.

**Comment by alanmels** [comment]
Please give a try to latest dev or https://github.com/backdrop-contrib/sso/releases/tag/1.x-2.0.0
