### ISSUE TITLE
Not working with actual readme instructions

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/sso#6]
Readme says you have to config $cookie_domain for each subdomain. If you count www as a subdomain it's ok, but if you do like me, that don't like the www, main domain is a domain, not a subdomain. I would make sure that readme says that the cookie_domain settings needs to get set for each domain and subdomain.

**Comment by alanmels** [comment]
Had already been fixed on dev. See https://github.com/backdrop-contrib/sso/commit/01b136b60c8b951ed9cda8797275c627587a0069
